AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Stack for a AWS Lambdas using Java and NodeJS.

Resources:
  JavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.sebastianhesse.examples.JavaHelloWorldHandler
      Runtime: java8
      Timeout: 10
      CodeUri: ./target/target.jar
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetJavaResource:
          Type: Api
          Properties:
            Path: /java
            Method: get