AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Stack for AWS Lambdas functions using Java and Node.js.

Resources:
  NodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 10
      CodeUri: ./node-backend/target
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetNodeResource:
          Type: Api
          Properties:
            Path: /node
            Method: get

  JavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: de.sebastianhesse.examples.JavaHelloWorldHandler
      Runtime: java8
      Timeout: 10
      CodeUri: ./java-backend/target/target.jar
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetJavaResource:
          Type: Api
          Properties:
            Path: /java
            Method: get


Outputs:
  TestUrlOne:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/node
    Description: The url to invoke your Node Lambda function.

  TestUrlTwo:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/java
    Description: The url to invoke your Java Lambda function.
